### ISSUE TITLE
"Operation System" is "Operating System", isn't it?

### ISSUE THREAD

**Issue by offnaria** [Iris2664/iris2664.com#1]
はじめまして。
ホームページを拝見しまして、気になった点があります。

https://github.com/Iris2664/iris2664.com/blob/d57a576b97a57dcce1342b47d3599b672334289a/index.html#L78

この「オペレーションシステム」とは、「オペレーティングシステム」のことですか？

**Comment by Iris2664** [comment]
> はじめまして。
> ホームページを拝見しまして、気になった点があります。
> 
> https://github.com/Iris2664/iris2664.com/blob/d57a576b97a57dcce1342b47d3599b672334289a/index.html#L78
> 
> この「オペレーションシステム」とは、「オペレーティングシステム」のことですか？

あ！誤字です！
ご指摘ありがとうございます🙇
